### ISSUE TITLE
Unpaired Video Translation

### ISSUE THREAD

**Issue by AloshkaD** [thunil/TecoGAN#106]
Thanks for the great work.
I don't see the Unpaired Video Translation code in the repo., is it available somewhere? I would like to benchmark it against an algorithm I've developed.

**Comment by zgzxy001** [comment]
Hi @AloshkaD , did you find the Unpaired Video Translation code? Thanks!

**Comment by AloshkaD** [comment]
@zgzxy001 It's not published yet.
