### ISSUE TITLE
Is upscale_two possible?

### ISSUE THREAD

**Issue by whyboris** [thunil/TecoGAN#12]
*Could you comment whether it's possible to modify only a bit of the code and continue using your pre-trained model to "upscale_two"?*

Thank you so much for *TecoGAN* 🙇 
I've successfully upscaled sequences of images with your pre-trained model 🚀 

The current code hard-codes [`upscale_four`](https://github.com/thunil/TecoGAN/blob/dfee612a3249677293309f9c3d901ad6224d3d9f/lib/ops.py#L126) - quadrupling the width and quadrupling the height.

I have attempted several code changes, starting with changing [`output_shape`](https://github.com/thunil/TecoGAN/blob/dfee612a3249677293309f9c3d901ad6224d3d9f/main.py#L187) to be `*2` (not `*4`) of the input shape.

Needless to say, minor tinkering keeps resulting in incompatible shapes, e.g:
```
Dimension 1 in both shapes must be equal, but are 288 and 576. Shapes are [1,288,360,3] and [1,576,720,3]. for 'generator/Assign_1' (op: 'Assign') with input shapes: [1,288,360,3], [1,576,720,3].
```

I suspect I might be trying a fool's errand (since the model was trained to upsample x4 rather than x2). Please let me know 🙇 

ps - In your paper you write:
> In our case, the outputs have four times the resolution of the inputs.

But based on the code, it seems that you may have increased the resolution 16 times? 

pps - minor grammatical error in the paper:
> In order to avoid the this undesirable case

**Comment by RachelCmy** [comment]
Hi,

right, although the algorithm is not for a fixed resolution, the implementation here is now fixed to a factor of 4 in each dimension and increases the resolution for 16 times.

The code has to be changed consistently for many places for a factor of 2 and the published model cannot be used. An easier solution is to get the 4x result first, and down-scale it to 2x resolution.

Thank you for the ps and pps! We will update the paper in a future version.
