### ISSUE TITLE
Issue with dataprep command in readme

### ISSUE THREAD

**Issue by nwstgeo** [thunil/TecoGAN#13]
The last command in “1. Prepare the Training Data” in the readme,

python3 dataPrepare.py --start_id 2000 --duration 120 --REMOVE --disk_path TrainingDataPath

Is missing some slashes in the disk path flag, and causes the dataPrepare.py script to download mp4’s titled TrainingDataPath*vimeoID*.mp4 into the master folder instead of downloading them as *vimeoID*.mp4 in the actual TrainingDataPath folder, thus causing them to not be found later in the script & causing the script to fail to extract any scenes. This can be fixed by using the following command instead:

python3 dataPrepare.py --start_id 2000 --duration 120 --REMOVE --disk_path ./TrainingDataPath/

Which simply corrects the disk path flag and allows dataPrepare.py to work as intended

**Comment by RachelCmy** [comment]
Thank you for the information. A fix is just committed.
