### ISSUE TITLE
Tutorial and windows build?

### ISSUE THREAD

**Issue by shadowzoom** [thunil/TecoGAN#24]
Can please somebody record a short video tut (just show what you doing, dosnt necessery to speak/write)

**Comment by shadowzoom** [comment]
Figure it out

**Comment by EdisonBing** [comment]
Installed on win10 using anaconda3 following installation instructions provide by authors with changes to runGan.py cmd as referred to in forum(add shell=True)

**Comment by aakh1361** [comment]
https://github.com/Sanaxen/tecoGAN_app
