### ISSUE TITLE
No GPU utilization for inference

### ISSUE THREAD

**Issue by JonathanLehner** [thunil/TecoGAN#31]
is the inference using GPU?
on my PC it is very slow - around 1 second per frame - despite having a GTX1080ti and the GPU utilization is very slow (always lower than 10%).

**Comment by jcai20** [comment]
It has GPU model for inference. My testing takes about 24 fps.

**Comment by JonathanLehner** [comment]
are you sure it uses the gpu? I get 24 fps with gpu i think. nvidia-smi shows almost no gpu activity. and tensorflow shows detected gpu devices 0. i installed cuda 10.1 and cudnn but it didn't heelp

**Comment by jcai20** [comment]
Yes, i am sure it's using GPU. I used "watch nvidia-smi", it has gpu activity. I am using tf1.14 and cuda 10.0.

**Comment by JonathanLehner** [comment]
I re-installed cuda 10.0 according to here https://www.tensorflow.org/install/gpu#software_requirements and now it works
