### ISSUE TITLE
Please make a google colab

### ISSUE THREAD

**Issue by shadowzoom** [thunil/TecoGAN#32]
Please make a google colab, thanks

**Comment by FrankLinxzx** [comment]
> Please make a google colab, thanks

https://colab.research.google.com/drive/1arRAJUPBC3a3l2iGghbs3CqDjdD1IQ6y?usp=sharing#scrollTo=e9qFFxDMz6LL

**Comment by shadowzoom** [comment]
> > Please make a google colab, thanks
> 
> https://colab.research.google.com/drive/1arRAJUPBC3a3l2iGghbs3CqDjdD1IQ6y?usp=sharing#scrollTo=e9qFFxDMz6LL

Thanks!!
