### ISSUE TITLE
when runGan.py i find same SyntaxError

### ISSUE THREAD

**Issue by liyang53719** [thunil/TecoGAN#4]
when i run
 `$ python runGan.py 1`
it return
 `Testing test case 1
  File "main.py", line 56
    os.mkdir(FLAGS.output_dubuntu-drivers devicesir)
                                                  ^
SyntaxError: invalid syntax
`
Is some thing wrong I made?

**Comment by Akrog** [comment]
Did you change the `main.py` file?  Because the [actual code](https://github.com/thunil/TecoGAN/blob/master/main.py#L56) reads as `os.mkdir(FLAGS.output_dir)`, and it looks like you have added `ubuntu-drivers devices` in there.
