### ISSUE TITLE
Question about input & output resolution

### ISSUE THREAD

**Issue by jahwanoh** [thunil/TecoGAN#69]
Thank you for sharing this awesome work.
I succeed to test the code on the docker environment.

Just for the quick test, I tried with input(519x292) to upscale(2076x1168).
However, it fails when I input (2076x1168) to upscale by factor 4.

I didn't touch any code but only input.
Should I modify some part for a quick test with larger resolution input?

Thank you for the support.

**Comment by CaryKnoop** [comment]
I suspect it is limited by the available GPU memory.

**Comment by jahwanoh** [comment]
thank you. heuristically, it refuses to process when the output size is over 4k (width).
