### ISSUE TITLE
How to resume training?

### ISSUE THREAD

**Issue by flutide** [thunil/TecoGAN#72]
Hi everyone.

After some serious fiddling to get the code running on a Win10 machine (and using the GPU), I ran into the minor problem of power failure in the building. This was part way through running "_python3 runGan.py 3_".

**Now, how do I resume training from the last saved checkpoint?**

I can see 6 stored check points on disk, last one being "model-50000".

**Comment by flutide** [comment]
Im somewhat confused by this part in runGan.py:

  

> cmd1 += [ # based on a pre-trained FRVSR model. Here we want to train a new adversarial training
>         "--pre_trained_model", # True
>         "--checkpoint", FRVSRModel,
>     ]
>     
>     # the following can be used to train TecoGAN continuously
>     # old_model = "model/ex_TecoGANmm-dd-hh/model-xxxxxxx" 
>     # cmd1 += [ # Here we want to train continuously
>     #     "--nopre_trained_model", # False
>     #     "--checkpoint", old_model,
>     # ]
    
Should there be a "true" or "false" applied after --pre_trained_model and --nopre_trained_model? Or just un-comment last paragraph and set the path to some saved checkpoint?

**Comment by tom-doerr** [comment]
My guess would be that there shouldn't be true or false after those options, otherwise it wouldn't make sense to have both --pre_trained_model and --nopre_trained_model. You probably just need to uncomment the block and adjust the paths.

**Comment by flutide** [comment]
Thank you Tom. I'll give it another go in... 154h when my trial run is over

**Comment by flutide** [comment]
FYI, I figured it out.

Forgot to comment out 

> "--pre_trained_model"

 on line 201 in runGan.py. It is default "False" in main.

Then just pass --checkpoint with path to saved model.

Works like a charm.

**Comment by alessiapacca** [comment]
hey @flutide , i did exactly like you did, but when I train it always says 
`Loading weights from the pre-trained model to start a new training...
`

did this also happened to you? 
shouldn't it "continue" the previous training? 
Isn't it starting again from the start like this? 
i mean, it says epoch 1 again when I load the checkpoint

**Comment by flutide** [comment]
> hey @flutide , i did exactly like you did, but when I train it always says
> `Loading weights from the pre-trained model to start a new training... `
> 
> did this also happened to you?
> shouldn't it "continue" the previous training?
> Isn't it starting again from the start like this?
> i mean, it says epoch 1 again when I load the checkpoint

Hi. Sorry about late reply. You need to make sure "--pre_trained_model" is commented out, otherwise it will reset ADAM parameters and the step counter.
