### ISSUE TITLE
Problems training TecoGAN in Docker

### ISSUE THREAD

**Issue by flutide** [thunil/TecoGAN#73]
I'm running the docker-version under WSL2, Ubutu 16.04. 

GPU is found in this environment, and I've tried it with a simple MNIST dataset and TF. Training on GPU in that case works, VRAM is allocated  etc. 

However, running "python3 runGan.py 3" does not seem to push anything into VRAM. The script generates the network, restores VGG19, saves a checkpoint and then exits without error or warning message. 

Any ideas?

**Comment by tom-doerr** [comment]
Hard to say what the issue could be without any error message.
Some ideas:
- Tensorflow runs out of memory. Training the TecoGAN takes ~11GB of VRAM with the standard settings.
- The training script can't find the training data, you could try to run `python3 runGan.py 0` once again and check if there are errors when downloading.
- Ubuntu 16.04 is too old, you could try to use 18.04 or 20.04.

However I usually would expect some error message in all cases.

**Comment by flutide** [comment]
Thanks for a quick reply Tom! 

- Gees, 11 GB. My meager 1660 only holds 6 GB. Looks like time for an upgrade with the 3090 on the horizon. 
- I carefully looked at "TrainingDataPath", changing it and looking at the output. This one looks ok though, correct path. Some movies did not download, I created my own short 120 frame clips to fill out the rest. 
- I'll change Ubuntu dist.

I'll update if or when I find a solution to the above problem.

**Comment by flutide** [comment]
Installed Ubuntu 20.04, Docker set up and running correctly, code verbatim from git repo. Still same "error". 
**Complaints about no NUMA support with kernel.**  Total run time about 4 min. Output below with os.environ['TF_CPP_MIN_LOG_LEVEL'] = '1' as only change to source code. 

------------------------------------------------------------------------------------------------------------------------
root@707d32010bab:/TecoGAN# python3 runGan.py 3
Testing test case 3
Delete existing folder ex_TecoGAN09-07-21/?(Y/N)
n
ex_TecoGAN09-07-21_1/
/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Preparing train_data
[Config] Use random crop
[Config] Use random crop
[Config] Use random flip
Sequenced batches: 27500, sequence length: 10
Preparing validation_data
[Config] Use random crop
[Config] Use random crop
[Config] Use random flip
Sequenced batches: 4400, sequence length: 10
tData count = 27500, steps per epoch 6875
variable not found in ckpt: generator/generator_unit/resblock_11/conv_1/Conv/weights:0
Assign Zero of (3, 3, 64, 64)
variable not found in ckpt: generator/generator_unit/resblock_11/conv_1/Conv/biases:0
Assign Zero of (64,)
variable not found in ckpt: generator/generator_unit/resblock_11/conv_2/Conv/weights:0
Assign Zero of (3, 3, 64, 64)
variable not found in ckpt: generator/generator_unit/resblock_11/conv_2/Conv/biases:0
Assign Zero of (64,)
variable not found in ckpt: generator/generator_unit/resblock_12/conv_1/Conv/weights:0
Assign Zero of (3, 3, 64, 64)
variable not found in ckpt: generator/generator_unit/resblock_12/conv_1/Conv/biases:0
Assign Zero of (64,)
variable not found in ckpt: generator/generator_unit/resblock_12/conv_2/Conv/weights:0
Assign Zero of (3, 3, 64, 64)
variable not found in ckpt: generator/generator_unit/resblock_12/conv_2/Conv/biases:0
Assign Zero of (64,)
variable not found in ckpt: generator/generator_unit/resblock_13/conv_1/Conv/weights:0
Assign Zero of (3, 3, 64, 64)
variable not found in ckpt: generator/generator_unit/resblock_13/conv_1/Conv/biases:0
Assign Zero of (64,)
variable not found in ckpt: generator/generator_unit/resblock_13/conv_2/Conv/weights:0
Assign Zero of (3, 3, 64, 64)
variable not found in ckpt: generator/generator_unit/resblock_13/conv_2/Conv/biases:0
Assign Zero of (64,)
variable not found in ckpt: generator/generator_unit/resblock_14/conv_1/Conv/weights:0
Assign Zero of (3, 3, 64, 64)
variable not found in ckpt: generator/generator_unit/resblock_14/conv_1/Conv/biases:0
Assign Zero of (64,)
variable not found in ckpt: generator/generator_unit/resblock_14/conv_2/Conv/weights:0
Assign Zero of (3, 3, 64, 64)
variable not found in ckpt: generator/generator_unit/resblock_14/conv_2/Conv/biases:0
Assign Zero of (64,)
variable not found in ckpt: generator/generator_unit/resblock_15/conv_1/Conv/weights:0
Assign Zero of (3, 3, 64, 64)
variable not found in ckpt: generator/generator_unit/resblock_15/conv_1/Conv/biases:0
Assign Zero of (64,)
variable not found in ckpt: generator/generator_unit/resblock_15/conv_2/Conv/weights:0
Assign Zero of (3, 3, 64, 64)
variable not found in ckpt: generator/generator_unit/resblock_15/conv_2/Conv/biases:0
Assign Zero of (64,)
variable not found in ckpt: generator/generator_unit/resblock_16/conv_1/Conv/weights:0
Assign Zero of (3, 3, 64, 64)
variable not found in ckpt: generator/generator_unit/resblock_16/conv_1/Conv/biases:0
Assign Zero of (64,)
variable not found in ckpt: generator/generator_unit/resblock_16/conv_2/Conv/weights:0
Assign Zero of (3, 3, 64, 64)
variable not found in ckpt: generator/generator_unit/resblock_16/conv_2/Conv/biases:0
Assign Zero of (64,)
Prepare to load 100 weights from the pre-trained model for generator and fnet
Prepare to load 0 weights from the pre-trained model for discriminator
Finish building the network.
**2020-09-07 21:56:18.301042: E tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:884] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.**
Scope generator:
Variable: generator/generator_unit/input_stage/conv/Conv/weights:0
Shape: [3, 3, 51, 64]
Variable: generator/generator_unit/input_stage/conv/Conv/biases:0
Shape: [64]
Variable: generator/generator_unit/resblock_1/conv_1/Conv/weights:0
Shape: [3, 3, 64, 64]
Variable: generator/generator_unit/resblock_1/conv_1/Conv/biases:0
Shape: [64]
Variable: generator/generator_unit/resblock_1/conv_2/Conv/weights:0
Shape: [3, 3, 64, 64]
Variable: generator/generator_unit/resblock_1/conv_2/Conv/biases:0
Shape: [64]
Variable: generator/generator_unit/resblock_2/conv_1/Conv/weights:0
Shape: [3, 3, 64, 64]
Variable: generator/generator_unit/resblock_2/conv_1/Conv/biases:0
Shape: [64]
Variable: generator/generator_unit/resblock_2/conv_2/Conv/weights:0
Shape: [3, 3, 64, 64]
Variable: generator/generator_unit/resblock_2/conv_2/Conv/biases:0
Shape: [64]
Variable: generator/generator_unit/resblock_3/conv_1/Conv/weights:0
Shape: [3, 3, 64, 64]
Variable: generator/generator_unit/resblock_3/conv_1/Conv/biases:0
Shape: [64]
Variable: generator/generator_unit/resblock_3/conv_2/Conv/weights:0
Shape: [3, 3, 64, 64]
Variable: generator/generator_unit/resblock_3/conv_2/Conv/biases:0
Shape: [64]
Variable: generator/generator_unit/resblock_4/conv_1/Conv/weights:0
Shape: [3, 3, 64, 64]
Variable: generator/generator_unit/resblock_4/conv_1/Conv/biases:0
Shape: [64]
Variable: generator/generator_unit/resblock_4/conv_2/Conv/weights:0
Shape: [3, 3, 64, 64]
Variable: generator/generator_unit/resblock_4/conv_2/Conv/biases:0
Shape: [64]
Variable: generator/generator_unit/resblock_5/conv_1/Conv/weights:0
Shape: [3, 3, 64, 64]
Variable: generator/generator_unit/resblock_5/conv_1/Conv/biases:0
Shape: [64]
Variable: generator/generator_unit/resblock_5/conv_2/Conv/weights:0
Shape: [3, 3, 64, 64]
Variable: generator/generator_unit/resblock_5/conv_2/Conv/biases:0
Shape: [64]
Variable: generator/generator_unit/resblock_6/conv_1/Conv/weights:0
Shape: [3, 3, 64, 64]
Variable: generator/generator_unit/resblock_6/conv_1/Conv/biases:0
Shape: [64]
Variable: generator/generator_unit/resblock_6/conv_2/Conv/weights:0
Shape: [3, 3, 64, 64]
Variable: generator/generator_unit/resblock_6/conv_2/Conv/biases:0
Shape: [64]
Variable: generator/generator_unit/resblock_7/conv_1/Conv/weights:0
Shape: [3, 3, 64, 64]
Variable: generator/generator_unit/resblock_7/conv_1/Conv/biases:0
Shape: [64]
Variable: generator/generator_unit/resblock_7/conv_2/Conv/weights:0
Shape: [3, 3, 64, 64]
Variable: generator/generator_unit/resblock_7/conv_2/Conv/biases:0
Shape: [64]
Variable: generator/generator_unit/resblock_8/conv_1/Conv/weights:0
Shape: [3, 3, 64, 64]
Variable: generator/generator_unit/resblock_8/conv_1/Conv/biases:0
Shape: [64]
Variable: generator/generator_unit/resblock_8/conv_2/Conv/weights:0
Shape: [3, 3, 64, 64]
Variable: generator/generator_unit/resblock_8/conv_2/Conv/biases:0
Shape: [64]
Variable: generator/generator_unit/resblock_9/conv_1/Conv/weights:0
Shape: [3, 3, 64, 64]
Variable: generator/generator_unit/resblock_9/conv_1/Conv/biases:0
Shape: [64]
Variable: generator/generator_unit/resblock_9/conv_2/Conv/weights:0
Shape: [3, 3, 64, 64]
Variable: generator/generator_unit/resblock_9/conv_2/Conv/biases:0
Shape: [64]
Variable: generator/generator_unit/resblock_10/conv_1/Conv/weights:0
Shape: [3, 3, 64, 64]
Variable: generator/generator_unit/resblock_10/conv_1/Conv/biases:0
Shape: [64]
Variable: generator/generator_unit/resblock_10/conv_2/Conv/weights:0
Shape: [3, 3, 64, 64]
Variable: generator/generator_unit/resblock_10/conv_2/Conv/biases:0
Shape: [64]
Variable: generator/generator_unit/resblock_11/conv_1/Conv/weights:0
Shape: [3, 3, 64, 64]
Variable: generator/generator_unit/resblock_11/conv_1/Conv/biases:0
Shape: [64]
Variable: generator/generator_unit/resblock_11/conv_2/Conv/weights:0
Shape: [3, 3, 64, 64]
Variable: generator/generator_unit/resblock_11/conv_2/Conv/biases:0
Shape: [64]
Variable: generator/generator_unit/resblock_12/conv_1/Conv/weights:0
Shape: [3, 3, 64, 64]
Variable: generator/generator_unit/resblock_12/conv_1/Conv/biases:0
Shape: [64]
Variable: generator/generator_unit/resblock_12/conv_2/Conv/weights:0
Shape: [3, 3, 64, 64]
Variable: generator/generator_unit/resblock_12/conv_2/Conv/biases:0
Shape: [64]
Variable: generator/generator_unit/resblock_13/conv_1/Conv/weights:0
Shape: [3, 3, 64, 64]
Variable: generator/generator_unit/resblock_13/conv_1/Conv/biases:0
Shape: [64]
Variable: generator/generator_unit/resblock_13/conv_2/Conv/weights:0
Shape: [3, 3, 64, 64]
Variable: generator/generator_unit/resblock_13/conv_2/Conv/biases:0
Shape: [64]
Variable: generator/generator_unit/resblock_14/conv_1/Conv/weights:0
Shape: [3, 3, 64, 64]
Variable: generator/generator_unit/resblock_14/conv_1/Conv/biases:0
Shape: [64]
Variable: generator/generator_unit/resblock_14/conv_2/Conv/weights:0
Shape: [3, 3, 64, 64]
Variable: generator/generator_unit/resblock_14/conv_2/Conv/biases:0
Shape: [64]
Variable: generator/generator_unit/resblock_15/conv_1/Conv/weights:0
Shape: [3, 3, 64, 64]
Variable: generator/generator_unit/resblock_15/conv_1/Conv/biases:0
Shape: [64]
Variable: generator/generator_unit/resblock_15/conv_2/Conv/weights:0
Shape: [3, 3, 64, 64]
Variable: generator/generator_unit/resblock_15/conv_2/Conv/biases:0
Shape: [64]
Variable: generator/generator_unit/resblock_16/conv_1/Conv/weights:0
Shape: [3, 3, 64, 64]
Variable: generator/generator_unit/resblock_16/conv_1/Conv/biases:0
Shape: [64]
Variable: generator/generator_unit/resblock_16/conv_2/Conv/weights:0
Shape: [3, 3, 64, 64]
Variable: generator/generator_unit/resblock_16/conv_2/Conv/biases:0
Shape: [64]
Variable: generator/generator_unit/conv_tran2highres/conv_tran1/Conv2d_transpose/weights:0
Shape: [3, 3, 64, 64]
Variable: generator/generator_unit/conv_tran2highres/conv_tran1/Conv2d_transpose/biases:0
Shape: [64]
Variable: generator/generator_unit/conv_tran2highres/conv_tran2/Conv2d_transpose/weights:0
Shape: [3, 3, 64, 64]
Variable: generator/generator_unit/conv_tran2highres/conv_tran2/Conv2d_transpose/biases:0
Shape: [64]
Variable: generator/generator_unit/output_stage/conv/Conv/weights:0
Shape: [3, 3, 64, 3]
Variable: generator/generator_unit/output_stage/conv/Conv/biases:0
Shape: [3]
total size: 1286723
Scope fnet:
Variable: fnet/autoencode_unit/encoder_1/conv_1/Conv/weights:0
Shape: [3, 3, 6, 32]
Variable: fnet/autoencode_unit/encoder_1/conv_1/Conv/biases:0
Shape: [32]
Variable: fnet/autoencode_unit/encoder_1/conv_2/Conv/weights:0
Shape: [3, 3, 32, 32]
Variable: fnet/autoencode_unit/encoder_1/conv_2/Conv/biases:0
Shape: [32]
Variable: fnet/autoencode_unit/encoder_2/conv_1/Conv/weights:0
Shape: [3, 3, 32, 64]
Variable: fnet/autoencode_unit/encoder_2/conv_1/Conv/biases:0
Shape: [64]
Variable: fnet/autoencode_unit/encoder_2/conv_2/Conv/weights:0
Shape: [3, 3, 64, 64]
Variable: fnet/autoencode_unit/encoder_2/conv_2/Conv/biases:0
Shape: [64]
Variable: fnet/autoencode_unit/encoder_3/conv_1/Conv/weights:0
Shape: [3, 3, 64, 128]
Variable: fnet/autoencode_unit/encoder_3/conv_1/Conv/biases:0
Shape: [128]
Variable: fnet/autoencode_unit/encoder_3/conv_2/Conv/weights:0
Shape: [3, 3, 128, 128]
Variable: fnet/autoencode_unit/encoder_3/conv_2/Conv/biases:0
Shape: [128]
Variable: fnet/autoencode_unit/decoder_1/conv_1/Conv/weights:0
Shape: [3, 3, 128, 256]
Variable: fnet/autoencode_unit/decoder_1/conv_1/Conv/biases:0
Shape: [256]
Variable: fnet/autoencode_unit/decoder_1/conv_2/Conv/weights:0
Shape: [3, 3, 256, 256]
Variable: fnet/autoencode_unit/decoder_1/conv_2/Conv/biases:0
Shape: [256]
Variable: fnet/autoencode_unit/decoder_2/conv_1/Conv/weights:0
Shape: [3, 3, 256, 128]
Variable: fnet/autoencode_unit/decoder_2/conv_1/Conv/biases:0
Shape: [128]
Variable: fnet/autoencode_unit/decoder_2/conv_2/Conv/weights:0
Shape: [3, 3, 128, 128]
Variable: fnet/autoencode_unit/decoder_2/conv_2/Conv/biases:0
Shape: [128]
Variable: fnet/autoencode_unit/decoder_3/conv_1/Conv/weights:0
Shape: [3, 3, 128, 64]
Variable: fnet/autoencode_unit/decoder_3/conv_1/Conv/biases:0
Shape: [64]
Variable: fnet/autoencode_unit/decoder_3/conv_2/Conv/weights:0
Shape: [3, 3, 64, 64]
Variable: fnet/autoencode_unit/decoder_3/conv_2/Conv/biases:0
Shape: [64]
Variable: fnet/autoencode_unit/output_stage/conv1/Conv/weights:0
Shape: [3, 3, 64, 32]
Variable: fnet/autoencode_unit/output_stage/conv1/Conv/biases:0
Shape: [32]
Variable: fnet/autoencode_unit/output_stage/conv2/Conv/weights:0
Shape: [3, 3, 32, 2]
Variable: fnet/autoencode_unit/output_stage/conv2/Conv/biases:0
Shape: [2]
total size: 1745506
Scope tdiscriminator:
Variable: tdiscriminator/discriminator_unit/input_stage/conv/Conv/weights:0
Shape: [3, 3, 27, 64]
Variable: tdiscriminator/discriminator_unit/input_stage/conv/Conv/biases:0
Shape: [64]
Variable: tdiscriminator/discriminator_unit/disblock_1/conv1/Conv/weights:0
Shape: [4, 4, 64, 64]
Variable: tdiscriminator/discriminator_unit/disblock_1/BatchNorm/beta:0
Shape: [64]
Variable: tdiscriminator/discriminator_unit/disblock_1/BatchNorm/moving_mean:0
Shape: [64]
Variable: tdiscriminator/discriminator_unit/disblock_1/BatchNorm/moving_variance:0
Shape: [64]
Variable: tdiscriminator/discriminator_unit/disblock_3/conv1/Conv/weights:0
Shape: [4, 4, 64, 64]
Variable: tdiscriminator/discriminator_unit/disblock_3/BatchNorm/beta:0
Shape: [64]
Variable: tdiscriminator/discriminator_unit/disblock_3/BatchNorm/moving_mean:0
Shape: [64]
Variable: tdiscriminator/discriminator_unit/disblock_3/BatchNorm/moving_variance:0
Shape: [64]
Variable: tdiscriminator/discriminator_unit/disblock_5/conv1/Conv/weights:0
Shape: [4, 4, 64, 128]
Variable: tdiscriminator/discriminator_unit/disblock_5/BatchNorm/beta:0
Shape: [128]
Variable: tdiscriminator/discriminator_unit/disblock_5/BatchNorm/moving_mean:0
Shape: [128]
Variable: tdiscriminator/discriminator_unit/disblock_5/BatchNorm/moving_variance:0
Shape: [128]
Variable: tdiscriminator/discriminator_unit/disblock_7/conv1/Conv/weights:0
Shape: [4, 4, 128, 256]
Variable: tdiscriminator/discriminator_unit/disblock_7/BatchNorm/beta:0
Shape: [256]
Variable: tdiscriminator/discriminator_unit/disblock_7/BatchNorm/moving_mean:0
Shape: [256]
Variable: tdiscriminator/discriminator_unit/disblock_7/BatchNorm/moving_variance:0
Shape: [256]
Variable: tdiscriminator/discriminator_unit/dense_layer_2/dense/kernel:0
Shape: [256, 1]
Variable: tdiscriminator/discriminator_unit/dense_layer_2/dense/kernel:0
Shape: [256, 1]
total size: 804096
Scope vgg_19:
Variable: vgg_19/conv1/conv1_1/weights:0
Shape: [3, 3, 3, 64]
Variable: vgg_19/conv1/conv1_1/biases:0
Shape: [64]
Variable: vgg_19/conv1/conv1_2/weights:0
Shape: [3, 3, 64, 64]
Variable: vgg_19/conv1/conv1_2/biases:0
Shape: [64]
Variable: vgg_19/conv2/conv2_1/weights:0
Shape: [3, 3, 64, 128]
Variable: vgg_19/conv2/conv2_1/biases:0
Shape: [128]
Variable: vgg_19/conv2/conv2_2/weights:0
Shape: [3, 3, 128, 128]
Variable: vgg_19/conv2/conv2_2/biases:0
Shape: [128]
Variable: vgg_19/conv3/conv3_1/weights:0
Shape: [3, 3, 128, 256]
Variable: vgg_19/conv3/conv3_1/biases:0
Shape: [256]
Variable: vgg_19/conv3/conv3_2/weights:0
Shape: [3, 3, 256, 256]
Variable: vgg_19/conv3/conv3_2/biases:0
Shape: [256]
Variable: vgg_19/conv3/conv3_3/weights:0
Shape: [3, 3, 256, 256]
Variable: vgg_19/conv3/conv3_3/biases:0
Shape: [256]
Variable: vgg_19/conv3/conv3_4/weights:0
Shape: [3, 3, 256, 256]
Variable: vgg_19/conv3/conv3_4/biases:0
Shape: [256]
Variable: vgg_19/conv4/conv4_1/weights:0
Shape: [3, 3, 256, 512]
Variable: vgg_19/conv4/conv4_1/biases:0
Shape: [512]
Variable: vgg_19/conv4/conv4_2/weights:0
Shape: [3, 3, 512, 512]
Variable: vgg_19/conv4/conv4_2/biases:0
Shape: [512]
Variable: vgg_19/conv4/conv4_3/weights:0
Shape: [3, 3, 512, 512]
Variable: vgg_19/conv4/conv4_3/biases:0
Shape: [512]
Variable: vgg_19/conv4/conv4_4/weights:0
Shape: [3, 3, 512, 512]
Variable: vgg_19/conv4/conv4_4/biases:0
Shape: [512]
Variable: vgg_19/conv5/conv5_1/weights:0
Shape: [3, 3, 512, 512]
Variable: vgg_19/conv5/conv5_1/biases:0
Shape: [512]
Variable: vgg_19/conv5/conv5_2/weights:0
Shape: [3, 3, 512, 512]
Variable: vgg_19/conv5/conv5_2/biases:0
Shape: [512]
Variable: vgg_19/conv5/conv5_3/weights:0
Shape: [3, 3, 512, 512]
Variable: vgg_19/conv5/conv5_3/biases:0
Shape: [512]
Variable: vgg_19/conv5/conv5_4/weights:0
Shape: [3, 3, 512, 512]
Variable: vgg_19/conv5/conv5_4/biases:0
Shape: [512]
total size: 20024384
VGG19 restored successfully!!
Loading weights from the pre-trained model to start a new training...
The first run takes longer time for training data loading...
Save initial checkpoint, before any training
root@707d32010bab:/TecoGAN#

**Comment by tom-doerr** [comment]
The missing NUMA support shouldn't be an issue.
The execution seems to fail somewhere in `main.py` (https://github.com/tom-doerr/TecoGAN/blob/master/main.py) in between lines `363` and `389`. If it would fail after `389` we would have seen the `Optimization starts!!!`... message. You could investigate where the execution fails by adding print statements or using a command-line debugger such as `pdb`.

**Comment by flutide** [comment]
Put in some prints here and there.
Main quits after line 365 "saver.save(save_sess, os.path.join(FLAGS.output_dir, 'model'), global_step=init_run_no)".
There is no sub-dir called 'model' created under "ex_TecoGAN09-xx-xx"

**Comment by tom-doerr** [comment]
My guess would be that it's a filesystem issue related to running inside docker inside WSL on a Windows filesystem.

**Comment by flutide** [comment]
Problem with trying several solutions at once is of course that once it works, you don't really know what did it. Here is my pragmatic solution to making it work with the GPU in Docker under WSL2:

- Run docker with "--rm --privileged"
- Create a .wslconfigfile under C:\users\'username'\ with "memory=xxGB" where xx=something large
- Reduce value of "--batch_size" in runGan.py to fit in VRAM

I also saw _some_ speed-up regarding file I/O with adding the WSL environment to the Windows Defender exclusion list.
