### ISSUE TITLE
Noisy output of TecoGAN

### ISSUE THREAD

**Issue by sfmth** [thunil/TecoGAN#74]
well, I used the pre-trained model, replaced 0001.png in the calendar with my own single image 180x144.
an this is what I got:
![photo_2020-09-09_17-10-11](https://user-images.githubusercontent.com/23662796/92601612-4dbc8880-f2c2-11ea-89a6-f74fe3920319.jpg)
is this a problem with the type of training data that is used for the pre-trained model? 
it is obviously messing up the compression noise, shouldn't we train it with this type of data as well?

also, I tried to change the output shape multiplier on line 187 in main.py and got errors how can we increase the output res?
and the i couldn't use any input image other than 180x144

**Comment by tom-doerr** [comment]
Regarding the noise: TecoGAN usually also uses information from the other images in the folder to generate the high resolution images. The artifacts you see could be TecoGAN trying to add the textures from the other calendar images.
Regarding the resolution: There already is an issue (https://github.com/thunil/TecoGAN/issues/69), maybe using more memory is an option for you.

**Comment by sfmth** [comment]
I just put the same image 10 times or so in the folder with nothing else, the results were almost the same, how can I train it with my own images? I think it has to learn this type of corruption in the image

well, my GPU only has 2GB I can't change that. I am trying to implement this into an image enhancing/super-resolution app and all the processing should be on the user side since I can't afford servers for it, but since it uses so much memory I don't know what to do, but I've seen deep learning models run in real-time on basically any hardware, is it just this model, or there are other tools I don't know about since I'm not that good at ML

**Comment by tom-doerr** [comment]
You could modify the training data that TecoGAN uses, but you probably won't be able to train it with only 2GB of VRAM.
Someone created a Google Colab notebook, you could try using that for development: https://colab.research.google.com/github/ak9250/TecoGAN/blob/master/Tecogan.ipynb
You probably need a lot less RAM when you just want to run inference, the 11GB are just for training with the default settings, but you would need to run it yourself to check that.

**Comment by sfmth** [comment]
I did run it in inference mode but my gpu memmory went up to 1.6gb, is that normal?

**Comment by tom-doerr** [comment]
Not sure, would have to test it.
