### ISSUE TITLE
How much memory is required?

### ISSUE THREAD

**Issue by farahats9** [thunil/TecoGAN#76]
Hi, I used the project to upscale a small 1300 frames video and it worked well. Now I am trying to upscale a larger video with 32k frames but it is getting stuck before detecting the shape of the input and my memory is getting full (8 GB ram) and also the swap is full (16 GB).

I am using tensorflow CPU and the LR video shape is 704x396. Is this a problem of low memory or something else? how can I make it run? I don't mind the long time since it will run on an old PC for hours.

**Comment by tom-doerr** [comment]
You could try to run TecoGAN only on the first 10 or so images from your second video. If that does work, then TecoGAN is probably just overwhelmed by the 32k frames and you could split it in batches and run TecoGAN on each individual batch.

**Comment by farahats9** [comment]
I see, it worked when I tried a smaller batch. I am assuming if I divide the video into smaller batches I will need to make sure there is no scene change in each batch? if that's the case is there any way to automate the scene change detection?

**Comment by tasiotas** [comment]
https://pyscenedetect.readthedocs.io/en/latest/

**Comment by tom-doerr** [comment]
Just wanted to send the same link :D 
This might also improve image quality, since TecoGAN assumes that the images in the input are from the same scene.

**Comment by farahats9** [comment]
Thank you all for the help.
