### ISSUE TITLE
Docker problem with runGan.py 4

### ISSUE THREAD

**Issue by flutide** [thunil/TecoGAN#80]
runGan.py 4 produces some error I cannot fathom. †

> root@b55c13b7b90f:/TecoGAN# python3 runGan.py 4
> /usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
>   from ._conv import register_converters as _register_converters
> Using TensorFlow backend.

> Preparing train_data
> [Config] Use random crop
> [Config] Use random crop
> [Config] Use random flip
> Sequenced batches: 28250, sequence length: 7
> Preparing validation_data
> [Config] Use random crop
> [Config] Use random crop
> [Config] Use random flip
> Sequenced batches: 5085, sequence length: 7
> tData count = 28250, steps per epoch 28250
> Traceback (most recent call last):
>   File "main.py", line 287, in <module>
>     Net = FRVSR( rdata.s_inputs, rdata.s_targets, FLAGS )
>   File "/TecoGAN/lib/Teco.py", line 522, in FRVSR
>     return TecoGAN(r_inputs, r_targets, FLAGS, False)
>   File "/TecoGAN/lib/Teco.py", line 434, in TecoGAN
>     update_loss = exp_averager.apply(update_list)
>   File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/moving_averages.py", line 388, in apply
>     raise ValueError("Moving average already computed for: %s" % var.name)
> ValueError: Moving average already computed for: generator_loss/content_loss/Mean:0

† probably just stupid.

**Comment by tom-doerr** [comment]
Thanks for reporting that! Always curious whether the docker environment works for everyone.
Can you run `python3 runGan.py 3`?
Did you follow the steps from the TecoGAN Docker readme or did you do something else?

**Comment by flutide** [comment]
I've been doing it step by step. `python3 runGan.py 3` works just fine (as per my previous, now resolved issue)

**Comment by tom-doerr** [comment]
Maybe it's because you modified `--batch_size`. You could try to set it to the original value.

**Comment by flutide** [comment]
Thanks for the suggestion. But nope, still the same with original `--batch_size `

**Comment by flutide** [comment]
Some questionable hack made it work.

Changed the `Dockerfile`  a bit:

`from tensorflow/tensorflow:1.15.0rc2-gpu-py3`
```
run pip3 install \
numpy>=1.14.3 \
scipy>=1.0.1 \
scikit-image>=0.13.0 \
matplotlib>=1.5.1 \
pandas>=0.23.1 \
Keras==2.1.3 \
torch>=0.4.0 \
torchvision>=0.2.1 \
opencv-python>=4.2.0.34 \
ipython>=7.4.0
```

and changed lib\ops.py according to suggestion in https://github.com/thunil/TecoGAN/issues/20#issuecomment-632592051

**Comment by tom-doerr** [comment]
Ironic that I recommended in that issue to use the docker environment.

**Comment by flutide** [comment]
A bit perhaps ¯\_(ツ)_/¯ But than again, I'm surprised it works at all (at my end) with GPU support under Win10 (20215.1000), WSL2, Docker etc.  Thanks again Tom for all valuable input, in this thread and the other ones!
