### ISSUE TITLE
Questions on your Optical Flow method

### ISSUE THREAD

**Issue by l-oneil** [thunil/TecoGAN#81]
Hi, thanks so much for pushing your full code to Github, it's fantastic work!

Just a couple of questions on the motion compensation you perform:

1. In this [line here](https://github.com/thunil/TecoGAN/blob/master/main.py#L213) why do you multiply your low resolution flow by 4, when upscaling by 4? 
`gen_flow = upscale_four(gen_flow_lr*4.0)`

2.  In this[ line here](https://github.com/thunil/TecoGAN/blob/67f868d0a77f41bb8f12d5d4bce36b833f4ba505/lib/frvsr.py#L39), you multiply the output of the `tanh` activation by `24.0` which you describe as "max velocity", am I correct in understanding this as the network being limited to compensate motion up to a displacement of +/- 24 pixels, but no further? 

Kind Regards, 
Liam

**Comment by itmo153277** [comment]
I am not related to the authors, but I from what I can understand:

1. The flow is just a coordinate offset map for warping. So when resolution is changed, naturally coordinates have to be scaled.
2. Tanh has value range from -1 to 1, so by multiplying it by 24 it makes the maximum offset 24 pixels (for non-scaled images).

**Comment by l-oneil** [comment]
Thanks, that's what I thought too!
