### ISSUE TITLE
how to get it working on windows

### ISSUE THREAD

**Issue by bestman8** [thunil/TecoGAN#82]
i have no coding experience or anything a vid or detailed instructions would be insanly nice especially on how to use it

**Comment by tom-doerr** [comment]
You could use the Windows Subsystem for Linux and follow the steps in my fork: https://github.com/tom-doerr/TecoGAN. 
This should make it easier to get started, but might still be very challenging if you have no coding experience.

**Comment by bestman8** [comment]
i found a different one that was pretty simple to install https://github.com/Sanaxen/tecoGAN_app
