### ISSUE TITLE
How to train this model?

### ISSUE THREAD

**Issue by ch135** [thunil/TecoGAN#9]
Thanks for your code. I have some questions. Fistly, how could i train this model. And how did you convert the video into an image for super resolution?  Finally, is it a composite video of super-resolution images?

I have been learning image super resolution before, knowing nothing about video super resolution, I hope to receive your reply in your busy schedule. Thank you very much.

**Comment by RachelCmy** [comment]
Hi,

our method is a frame-recurrent super-resolution for image sequences.
You can generate image sequences from videos by:
ffmpeg -i video.mp4 -vcodec png video_%04d.png
Our model processes the sequence frame by frame.
More details about how we achieve temporal coherence can be found in our paper.
 
To see the results, we recommend djv imaging(http://djv.sourceforge.net/Download.html).
