### ISSUE TITLE
Question: Has anybody used this for upscaling images only?

### ISSUE THREAD

**Issue by sephethus** [thunil/TecoGAN#96]
Will TecoGAN only work with video? I am seeing some people post about image upscaling so I assume this is possible but I have my own images to train with since the videos have long since been removed from the Vimeo source. Just wondering what would be needed to do this or how it needs to be organized in the training data folder to work.

**Comment by san-shriyan** [comment]
Same here, I have a dataset that I would like to train it with but unable to do so. I am a beginner and therefore any help would be appreciated. Also how can I verify a already trained model.
